<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.2</version>
        <relativePath/>
    </parent>

    <groupId>org.accmanager</groupId>
    <artifactId>acc-manager</artifactId>
    <version>0.7.0</version>
    <packaging>pom</packaging>

    <name>ACC Manager :: Parent</name>
    <description>The parent pom for the acc manager service</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <linkXRef>false</linkXRef>
        <input.yaml.file>acc-manager.yaml</input.yaml.file>
        <java.version>17</java.version>
        <maven.compiler.target>17</maven.compiler.target>
        <maven.compiler.source>17</maven.compiler.source>
        <spring.boot.version>3.4.2</spring.boot.version>
        <node.version>v20.18.1</node.version>
        <npm.version>10.8.2</npm.version>
        <frontend.maven.plugin.version>1.15.1</frontend.maven.plugin.version>
        <openapi.generator.version>7.11.0</openapi.generator.version>
        <maven.resources.plugin.version>3.3.1</maven.resources.plugin.version>

        <h2.version>2.3.232</h2.version>
        <postgres.version>42.7.5</postgres.version>
        <docker.java.version>3.3.4</docker.java.version>
        <cucumber.spring.version>7.15.0</cucumber.spring.version>
        <rest.assured.version>5.4.0</rest.assured.version>
        <jackson.databind.nullable.version>0.2.6</jackson.databind.nullable.version>
        <maven.source.plugin.version>3.3.1</maven.source.plugin.version>
        <maven.jar.plugin.version>3.4.2</maven.jar.plugin.version>
        <maven.compiler.plugin.version>3.13.0</maven.compiler.plugin.version>
        <junit-platform.version>1.11.4</junit-platform.version>
        <junit.jupiter.version>5.11.4</junit.jupiter.version>
        <maven.surefire.plugin.version>3.5.2</maven.surefire.plugin.version>
        <thymeleaf.security.version>3.1.3.RELEASE</thymeleaf.security.version>
        <handlebars.version>4.4.0</handlebars.version>
        <thymeleaf.layout.version>3.4.0</thymeleaf.layout.version>
        <j2html.version>1.6.0</j2html.version>
        <jetbrains.annotations.version>26.0.2</jetbrains.annotations.version>
        <javafaker.version>1.0.2</javafaker.version>
        <apache.commons.version>3.17.0</apache.commons.version>
        <webjar.locator.version>0.59</webjar.locator.version>
        <webjar.bootstrap.version>5.3.3</webjar.bootstrap.version>
        <webjar.bootstrap-icons.version>1.11.3</webjar.bootstrap-icons.version>
        <webjar.htmx.version>1.9.12</webjar.htmx.version>
        <webjar.hyperscript.version>0.9.13</webjar.hyperscript.version>
        <webjar.popper.version>2.11.7</webjar.popper.version>
        <maven.site.plugin.version>3.12.1</maven.site.plugin.version>
        <maven.assembly.plugin.version>3.7.1</maven.assembly.plugin.version>
        <maven.release-plugin.version>3.1.1</maven.release-plugin.version>
        <maven.dependency.plugin.version>3.8.1</maven.dependency.plugin.version>
        <maven.clean.plugin.version>3.4.1</maven.clean.plugin.version>
        <maven.deploy.plugin.version>3.1.3</maven.deploy.plugin.version>
        <maven.install.plugin.version>3.1.3</maven.install.plugin.version>
        <maven.failsafe.plugin.version>3.5.2</maven.failsafe.plugin.version>
        <maven.shade.plugin.version>3.6.0</maven.shade.plugin.version>
        <jakarta.validation.api.version>3.1.1</jakarta.validation.api.version>
        <jakarta.servlet.api.version>6.1.0</jakarta.servlet.api.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-parent</artifactId>
            <version>${spring.boot.version}</version>
            <type>pom</type>
        </dependency>
    </dependencies>

    <modules>
        <module>api</module>
        <module>service</module>
    </modules>

</project>
