spring:
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:database/data.sql
      mode: always
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true