accserver.control: executable
spring:
  batch:
    jdbc:
      initialize-schema: always
  security:
    user:
      password: 9k7nEa45dPzVuG64
logging:
  level:
    org:
      springframework:
        security: DEBUG
    log:
      hibernate:
        SQL: debug
        type: trace
