accserver.control: executable
spring:
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      password: 9k7nEa45dPzVuG64
logging:
  level:
    org:
      springframework:
        security: DEBUG
    log:
      hibernate:
        SQL: debug
        type: trace
