spring:
  datasource:
    schema: classpath:database/schema.sql
    platform: h2
    driver-class-name: org.h2.Driver
    username: accmanager
    password: accmanager
    url: jdbc:h2:file:/home/${docker.username}/acc-manager/database/acc-db-${spring.application.version};DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    log:
      hibernate:
        SQL: debug
        type: trace