docker:
  host: tcp://localhost:2375
  verify: false
external:
  server:
    address: http://localhost:8080
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /web/error
spring:
  application:
    name: acc-manager
    version: 0.7.0
  profiles:
    active: local,h2
    #active: local,postgres
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: acc-user
  thymeleaf:
    cache: false
    prefix: classpath:/static/web/
    darkMode: true
  mail:
    scheduler:
      persistence:
        enabled: false
        redis:
          embedded: false
          enabled: false
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: superPassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
management:
  endpoints:
    web:
      exposure:
        include: ['health', 'info', 'env', 'configprops']
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
    env:
      enabled: true