spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: h2-user
    password: gUfszrdzCBMwNSFH
    url: jdbc:h2:mem:acc-db;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:file:./database/acc-db-${spring.application.version};DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      #ddl-auto: none
      ddl-auto: update
      #ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    #defer-datasource-initialization: false
    database: h2
    show-sql: true
  sql:
    init:
      schema-locations: classpath:database/h2/schema.sql
      platform: h2
      continue-on-error: false
      data-locations: classpath:database/h2/data.sql
      mode: always
      #mode: embedded # - Does not execute inserts on app startup, for real database
      #mode: never # - Never execute inserts on app startup