docker:
  host: tcp://localhost:2375
  verify: false
server:
  port: 8080
spring:
  application:
    name: acc-manager
    version: 0.6.1
  profiles:
    active: local,h2
    #active: local,postgres
  security:
    user:
      name: acc-user
management:
  endpoints:
    web:
      exposure:
        include: ['health', 'info', 'env', 'configprops']
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
    env:
      enabled: true