spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/acc-db
  jpa:
    hibernate:
      #ddl-auto: none
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    #defer-datasource-initialization: false
    database: postgresql
    show-sql: true
  sql:
    init:
      schema-locations: classpath:database/schema.sql
      platform: postgres
      continue-on-error: true
      data-locations: classpath:database/data.sql
      mode: always
      #mode: embedded - Does not execute inserts on app startup, for real database
      #mode: never - Never execute inserts on app startup