docker:
  host: tcp://localhost:2375
  verify: false
  username: john
spring:
  application:
    name: acc-manager
    version: 0.5.0
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: local,h2
management:
  endpoints:
    web:
      exposure:
        include: ['health', 'info', 'env', 'configprops']
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
server:
  port: 8080