CREATE TABLE IF NOT EXISTS INSTANCES (
  INSTANCE_ID VARCHAR2(128 CHAR) NOT NULL UNIQUE,
  CONTAINER_NAME VARCHAR2(128 CHAR) NOT NULL,
  CONTAINER_STATE VARCHAR2(20 CHAR) NOT NULL,
  EVENT_ID VARCHAR2(128 CHAR) NOT NULL,
  ENTRIES_ID VARCHAR2(128 CHAR) NOT NULL,
  ASSISTS_ID VARCHAR2(128 CHAR) NOT NULL,
  BOP_ID VARCHAR2(128 CHAR) NOT NULL,
  CONFIG_ID VARCHAR2(128 CHAR) NOT NULL,
  SETTINGS_ID VARCHAR2(128 CHAR) NOT NULL,
  CONSTRAINT PK_INSTANCE PRIMARY KEY (INSTANCE_ID)
);

CREATE TABLE IF NOT EXISTS EVENTS (
  EVENT_ID VARCHAR2(128 CHAR) NOT NULL,
  EVENT_NAME VARCHAR2(256 CHAR) NOT NULL,
  TRACK VARCHAR2(128 CHAR) NOT NULL,
  PRE_RACE_WAITING_TIME_SEC NUMBER(10,0) NOT NULL,
  SESSION_OVER_TIME_SEC NUMBER(10,0) NOT NULL,
  AMBIENT_TEMP NUMBER(2,0) NOT NULL,
  TRACK_TEMP NUMBER(2,0) NOT NULL,
  CLOUD_LEVEL FLOAT NOT NULL,
  RAIN FLOAT NOT NULL,
  WEATHER_RANDOMNESS NUMBER(1,0) NOT NULL,
  POST_QUALY_TIME_SEC NUMBER(5,0) NOT NULL,
  POST_RACE_TIME_SEC NUMBER(5,0) NOT NULL,
  META_DATA VARCHAR2(128 CHAR) NOT NULL,
  SESSION_ID VARCHAR2(128 CHAR) NOT NULL,
  CONSTRAINT PK_EVENTS PRIMARY KEY (EVENT_ID),
  CONSTRAINT FK1_EVENTS FOREIGN KEY (EVENT_ID)
  REFERENCES INSTANCES (EVENT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SESSIONS (
  SESSION_ID VARCHAR2(128 CHAR) NOT NULL,
  HOUR_OF_DAY NUMBER(2,0) NOT NULL,
  DAY_OF_WEEKEND NUMBER(2,0) NOT NULL,
  TIME_MULTIPLIER NUMBER(2,0) NOT NULL,
  SESSION_TYPE VARCHAR2(1 CHAR) NOT NULL,
  SESSION_DURATION_MIN NUMBER(5,0) NOT NULL,
  CONSTRAINT FK1_SESSIONS FOREIGN KEY (SESSION_ID)
  REFERENCES EVENTS (SESSION_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DRIVER_ENTRIES (
  ENTRIES_ID VARCHAR2(128 CHAR) NOT NULL,
  ENTRY_ID VARCHAR2(128 CHAR) NOT NULL,
  FORCE_ENTRY_LIST NUMBER(1,0) NOT NULL,
  CONFIG_VERSION NUMBER(1,0) NOT NULL,
  CONSTRAINT PK_ENTRIES PRIMARY KEY (ENTRIES_ID),
  CONSTRAINT FK1_ENTRIES FOREIGN KEY (ENTRIES_ID)
  REFERENCES INSTANCES (ENTRIES_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DRIVER_ENTRY (
  ENTRY_ID VARCHAR2(128 CHAR) NOT NULL,
  DRIVER_ID VARCHAR2(128 CHAR) NOT NULL,
  RACE_NUMBER NUMBER(1,0) NOT NULL,
  FORCE_CAR_MODEL NUMBER(1,0) NOT NULL,
  OVERRIDE_DRIVER_INFO NUMBER(1,0) NOT NULL,
  CUSTOM_CAR VARCHAR2(50 CHAR) NOT NULL,
  OVERRIDE_CAR_MODEL_FOR_CUSTOM_CAR NUMBER(1,0) NOT NULL,
  IS_SERVER_ADMIN NUMBER(1,0) NOT NULL,
  DEFAULT_GRID_POSITION NUMBER(1,0) NOT NULL,
  BALLAST_KG NUMBER(1,0) NOT NULL,
  RESTRICTOR NUMBER(1,0) NOT NULL,
  CONSTRAINT PK_ENTRY PRIMARY KEY (ENTRY_ID),
  CONSTRAINT FK1_ENTRY FOREIGN KEY (ENTRY_ID)
  REFERENCES DRIVER_ENTRIES (ENTRY_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DRIVER (
  DRIVER_ID VARCHAR2(128 CHAR) NOT NULL,
  FIRST_NAME VARCHAR2(50 CHAR),
  LAST_NAME VARCHAR2(50 CHAR),
  SHORT_NAME VARCHAR2(50 CHAR),
  DRIVER_CATEGORY NUMBER(1,0),
  PLAYER_ID VARCHAR2(50 CHAR) NOT NULL,
  CONSTRAINT PK_DRIVER PRIMARY KEY (DRIVER_ID),
  CONSTRAINT FK1_DRIVER FOREIGN KEY (DRIVER_ID)
  REFERENCES DRIVER_ENTRY (DRIVER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ASSISTS (
  ASSISTS_ID VARCHAR2(128 CHAR) NOT NULL,
  STABILITY_CONTROL_LEVEL_MAX NUMBER(3,0) NOT NULL,
  DISABLE_AUTO_STEER NUMBER(1,0) NOT NULL,
  DISABLE_AUTO_LIGHTS NUMBER(1,0) NOT NULL,
  DISABLE_AUTO_WIPER NUMBER(1,0) NOT NULL,
  DISABLE_AUTO_ENGINE_START NUMBER(1,0) NOT NULL,
  DISABLE_AUTO_PIT_LIMITER NUMBER(1,0) NOT NULL,
  DISABLE_AUTO_GEAR NUMBER(1,0) NOT NULL,
  DISABLE_AUTO_CLUTCH NUMBER(1,0) NOT NULL,
  DISABLE_IDEAL_LINE NUMBER(1,0) NOT NULL,
  CONFIG_VERSION NUMBER(1,0) NOT NULL,
  CONSTRAINT PK_ASSISTS PRIMARY KEY (ASSISTS_ID),
  CONSTRAINT FK1_ASSISTS FOREIGN KEY (ASSISTS_ID)
  REFERENCES INSTANCES (ASSISTS_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BOP (
  BOP_ID VARCHAR2(128 CHAR) NOT NULL,
  BOP_ENTRY_ID VARCHAR2(128 CHAR) NOT NULL,
  DISABLE_AUTO_STEER NUMBER(1,0) NOT NULL,
  DISABLE_AUTO_LIGHTS NUMBER(1,0) NOT NULL,
  DISABLE_AUTO_WIPER NUMBER(1,0) NOT NULL,
  CONSTRAINT PK_BOP PRIMARY KEY (BOP_ID),
  CONSTRAINT FK1_BOP FOREIGN KEY (BOP_ID)
  REFERENCES INSTANCES (BOP_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BOP_ENTRY (
  BOP_ENTRY_ID VARCHAR2(128 CHAR) NOT NULL,
  TRACK VARCHAR2(50 CHAR) NOT NULL,
  CAR_MODEL NUMBER(3,0) NOT NULL,
  BALLEST NUMBER(3,0),
  RESTRICTOR NUMBER(2,0),
  CONSTRAINT PK_BOP_ENTRY PRIMARY KEY (BOP_ENTRY_ID),
  CONSTRAINT FK1_BOP_ENTRY FOREIGN KEY (BOP_ENTRY_ID)
  REFERENCES BOP (BOP_ENTRY_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CONFIG (
  CONFIG_ID VARCHAR2(128 CHAR) NOT NULL,
  UDP_PORT NUMBER(9,0) NOT NULL,
  TCP_PORT NUMBER(9,0) NOT NULL,
  MAX_CONNECTIONS NUMBER(3,0) NOT NULL,
  LAN_DISCOVERY NUMBER(1,0) NOT NULL,
  REGISTER_TO_LOBBY NUMBER(1,0) NOT NULL,
  CONFIG_VERSION NUMBER(1,0) NOT NULL,
  CONSTRAINT PK_CONFIG PRIMARY KEY (CONFIG_ID),
  CONSTRAINT FK1_CONFIG FOREIGN KEY (CONFIG_ID)
  REFERENCES INSTANCES (CONFIG_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SETTINGS (
  SETTINGS_ID VARCHAR2(128 CHAR) NOT NULL,
  SERVER_INSTANCE_NAME VARCHAR2(128 CHAR) NOT NULL,
  ADMIN_PASSWORD VARCHAR2(128 CHAR) NOT NULL,
  TRACK_MEDALS_REQUIREMENTS NUMBER(3,0) NOT NULL,
  SAFETY_RATING_REQUIREMENTS NUMBER(1,0) NOT NULL,
  PASSWORD VARCHAR2(128 CHAR) NOT NULL,
  SPECTATOR_PASSWORD VARCHAR2(128 CHAR) NOT NULL,
  MAX_CAR_SLOTS NUMBER(1,0) NOT NULL,
  DUMP_LEADER_BOARDS NUMBER(1,0) NOT NULL,
  IS_RACE_LOCKED NUMBER(1,0) NOT NULL,
  RANDOMIZE_TRACK_WHEN_EMPTY NUMBER(1,0) NOT NULL,
  CENTRAL_ENTRY_LIST_PATH VARCHAR2(128 CHAR) NOT NULL,
  ALLOW_AUTO_DQ NUMBER(1,0) NOT NULL,
  SHORT_FORMATION_LAP NUMBER(1,0) NOT NULL,
  CONFIG_VERSION NUMBER(1,0) NOT NULL,
  CONSTRAINT PK_SETTINGS PRIMARY KEY (SETTINGS_ID),
  CONSTRAINT FK1_SETTINGS FOREIGN KEY (SETTINGS_ID)
  REFERENCES INSTANCES (SETTINGS_ID) ON DELETE CASCADE
);